mode: predict
# load_ckpt: experiments/vm/checkpoint_95.pkl
load_ckpt: checkpoint_selection_L1_2.0/best_checkpoint.pkl

components:
  data: predict
  transform: predict
  system: vm
  model: vm

writer:
  __target__: vm
  save_dir: results
  save_name: denoised