mode: train

components:
  data: train_cached
  transform: residual_diffusion
  system: direct_residual_point_transformer
  model: direct_residual_point_transformer

loss:
  loss: 1.0

optimizer:
  __target__: adam
  lr: 0.0001

trainer:
  epochs: 100
